# Generated by Django 6.0.6 on 2026-06-27 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectmember',
            name='is_staff',
        ),
        migrations.AddField(
            model_name='projectmember',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('member', 'Member')], default='member', max_length=10),
        ),
    ]
