services:
  db:
    image: postgres:17
    container_name: mini_trello_db
    restart: unless-stopped

    environment:
      POSTGRES_DB: mini_trello
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
